server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: revision-audit
  devtools:
    restart:
      enabled: ${DEVELOPMENT_MODE:false}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:DEVELOPMENT}
  main:
    banner-mode: off
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:revision_audit}?useSSL=false&serverTimezone=UTC+8
    username: ${DB_USER:dev}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    properties:
      hibernate:
        format_sql: true
      envers:
        audit_table_suffix: _AUD
        revision_field_name: REV
        revision_type_field_name: REV_TYPE
        store_data_at_delete: true
        track_entities_changed_in_revision: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Jakarta